<a href="https://colab.research.google.com/github/Sujil75/Data-Analytics-Practices/blob/main/IPL_Data_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# **Load Data**

In [21]:
df = pd.read_csv("/content/ball_by_ball_ipl.csv", index_col=0)
df

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,1,0,NaN,NaN,4,1
1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,16,31,9,29,NaN,NaN,2,1
239689,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,2,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,22,31,10,29,NaN,NaN,6,1
239690,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,3,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,26,31,11,29,NaN,NaN,4,1
239691,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,4,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,27,31,12,29,NaN,NaN,1,1
239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson,YK Pathan,...,Sunrisers Hyderabad,1,32,27,30,12,NaN,NaN,1,1

In [22]:
df.head()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
0,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,1,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,1,0,NaN,NaN,4,1
1,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,2,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,2,0,NaN,NaN,0,1
2,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,3,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,3,0,NaN,NaN,0,1
3,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,4,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,4,0,4,0,NaN,NaN,0,1
4,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,1,1,5,RD Gaikwad,DP Conway,...,Chennai Super Kings,0,5,0,5,0,NaN,NaN,1,1

In [23]:
df.tail()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
239688,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,1,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,16,31,9,29,NaN,NaN,2,1
239689,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,2,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,22,31,10,29,NaN,NaN,6,1
239690,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,3,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,26,31,11,29,NaN,NaN,4,1
239691,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,4,YK Pathan,KS Williamson,...,Sunrisers Hyderabad,1,27,31,12,29,NaN,NaN,1,1
239692,1136596,2018-05-05,Rajiv Gandhi International Stadium,Delhi Daredevils,Sunrisers Hyderabad,2,20,5,KS Williamson,YK Pathan,...,Sunrisers Hyderabad,1,32,27,30,12,NaN,NaN,1,1

In [24]:
df.size

8149562

In [25]:
df.shape

(239693, 34)

In [26]:
df.ndim

2

In [27]:
df.columns

Index(['Match ID', 'Date', 'Venue', 'Bat First', 'Bat Second', 'Innings',
       'Over', 'Ball', 'Batter', 'Non Striker', 'Bowler', 'Batter Runs',
       'Extra Runs', 'Runs From Ball', 'Ball Rebowled', 'Extra Type', 'Wicket',
       'Method', 'Player Out', 'Innings Runs', 'Innings Wickets',
       'Target Score', 'Runs to Get', 'Balls Remaining', 'Winner',
       'Chased Successfully', 'Total Batter Runs', 'Total Non Striker Runs',
       'Batter Balls Faced', 'Non Striker Balls Faced', 'Player Out Runs',
       'Player Out Balls Faced', 'Bowler Runs Conceded', 'Valid Ball'],
      dtype='object')

In [28]:
df.dtypes

Match ID                     int64
Date                        object
Venue                       object
Bat First                   object
Bat Second                  object
Innings                      int64
Over                         int64
Ball                         int64
Batter                      object
Non Striker                 object
Bowler                      object
Batter Runs                  int64
Extra Runs                   int64
Runs From Ball               int64
Ball Rebowled                int64
Extra Type                  object
Wicket                       int64
Method                      object
Player Out                  object
Innings Runs                 int64
Innings Wickets              int64
Target Score                 int64
Runs to Get                float64
Balls Remaining              int64
Winner                      object
Chased Successfully          int64
Total Batter Runs            int64
Total Non Striker Runs       int64
Batter Balls Faced           int64
Non Striker Balls Faced      int64
Player Out Runs            float64
Player Out Balls Faced     float64
Bowler Runs Conceded         int64
Valid Ball                   int64
dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 239693 entries, 0 to 239692
Data columns (total 34 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Match ID                 239693 non-null  int64
 1   Date                     239693 non-null  object
 2   Venue                    239693 non-null  object
 3   Bat First                239693 non-null  object
 4   Bat Second               239693 non-null  object
 5   Innings                  239693 non-null  int64
 6   Over                     239693 non-null  int64
 7   Ball                     239693 non-null  int64
 8   Batter                   239693 non-null  object
 9   Non Striker              239693 non-null  object
 10  Bowler                   239693 non-null  object
 11  Batter Runs              239693 non-null  int64
 12  Extra Runs               239693 non-null  int64
 13  Runs From Ball           239693 non-null  int64
 14  Ball Rebowled            239693 non-null  int64
 15  Extra Type               239693 non-null  object
 16  Wicket                   239693 non-null  int64
 17  Method                   11827 non-null   object
 18  Player Out               11827 non-null   object
 19  Innings Runs             239693 non-null  int64
 20  Innings Wickets          239693 non-null  int64
 21  Target Score             239693 non-null  int64
 22  Runs to Get              115766 non-null  float64
 23  Balls Remaining          239693 non-null  int64
 24  Winner                   239693 non-null  object
 25  Chased Successfully      239693 non-null  int64
 26  Total Batter Runs        239693 non-null  int64
 27  Total Non Striker Runs   239693 non-null  int64
 28  Batter Balls Faced       239693 non-null  int64
 29  Non Striker Balls Faced  239693 non-null  int64
 30  Player Out Runs          11827 non-null   float64
 31  Player Out Balls Faced   11827 non-null   float64
 32  Bowler Runs Conceded     239693 non-null  int64
 33  Valid Ball               239693 non-null  int64
dtypes: float64(3), int64(20), object(11)
memory usage: 64.0+ MB

# **Data Cleaning**

In [30]:
df['Venue'].unique()

array(['Eden Gardens', 'De Beers Diamond Oval', 'Sharjah Cricket Stadium',
       'Wankhede Stadium', 'Feroz Shah Kotla', 'Holkar Cricket Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Maharashtra Cricket Association Stadium',
       'MA Chidambaram Stadium', 'Dubai International Cricket Stadium',
       'Kingsmead', 'Dr DY Patil Sports Academy', 'SuperSport Park',
       'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'M Chinnaswamy Stadium', 'Rajiv Gandhi International Stadium',
       'Brabourne Stadium', 'Sheikh Zayed Stadium',
       'M.Chinnaswamy Stadium', 'Punjab Cricket Association Stadium',
       'Narendra Modi Stadium', 'Arun Jaitley Stadium',
       'Barabati Stadium', 'Saurashtra Cricket Association Stadium',
       'Sardar Patel Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Green Park', 'Subrata Roy Sahara Stadium',
       'JSCA International Stadium Complex',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Zayed Cricket Stadium', 'Vidarbha Cricket Association Stadium',
       "St George's Park",
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
       'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval',
       'Buffalo Park', 'Barsapara Cricket Stadium'], dtype=object)

In [31]:
categorical_list = df.select_dtypes(include=["object", "category"]).columns.tolist()
categorical_list

['Date',
 'Venue',
 'Bat First',
 'Bat Second',
 'Batter',
 'Non Striker',
 'Bowler',
 'Extra Type',
 'Method',
 'Player Out',
 'Winner']

In [32]:
venue_map = {
    "M.Chinnaswamy Stadium": "M Chinnaswamy Stadium",
    "Zayed Cricket Stadium": "Sheikh Zayed Cricket Stadium",
    "Punjab Cricket Association Stadium": "Punjab Cricket Association IS Bindra Stadium",
    "Feroz Shah Kotla": "Arun Jaitley Stadium",
    "Sardar Patel Stadium": "Narendra Modi Stadium",
    "Subrata Roy Sahara Stadium": "Maharashtra Cricket Association Stadium",
    "MA Chidambaram Stadium": "M. A. Chidambaram Stadium",
    "Dr DY Patil Sports Academy": "Dr. DY Patil Sports Academy",
    "Green Park": "Green Park Stadium",
    "Rajiv Gandhi International Stadium": "Rajiv Gandhi International Cricket Stadium",
    "Holkar Cricket Stadium": "Holkar Stadium",
    "Barsapara Cricket Stadium": "Assam Cricket Association Stadium (Barsapara Cricket Stadium)"
}

df['Venue'].replace(venue_map, inplace = True)

In [33]:
df['Venue'].unique()

array(['Eden Gardens', 'De Beers Diamond Oval', 'Sharjah Cricket Stadium',
       'Wankhede Stadium', 'Arun Jaitley Stadium', 'Holkar Stadium',
       'Punjab Cricket Association IS Bindra Stadium',
       'Maharashtra Cricket Association Stadium',
       'M. A. Chidambaram Stadium', 'Dubai International Cricket Stadium',
       'Kingsmead', 'Dr. DY Patil Sports Academy', 'SuperSport Park',
       'Sawai Mansingh Stadium',
       'Shaheed Veer Narayan Singh International Stadium',
       'M Chinnaswamy Stadium',
       'Rajiv Gandhi International Cricket Stadium', 'Brabourne Stadium',
       'Sheikh Zayed Stadium', 'Narendra Modi Stadium',
       'Barabati Stadium', 'Saurashtra Cricket Association Stadium',
       'Himachal Pradesh Cricket Association Stadium', 'Nehru Stadium',
       'Green Park Stadium', 'JSCA International Stadium Complex',
       'Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket Stadium',
       'Sheikh Zayed Cricket Stadium',
       'Vidarbha Cricket Association Stadium', "St George's Park",
       'Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium',
       'New Wanderers Stadium', 'Newlands', 'OUTsurance Oval',
       'Buffalo Park',
       'Assam Cricket Association Stadium (Barsapara Cricket Stadium)'],
      dtype=object)

In [34]:
df['Bat First'].unique()

array(['Chennai Super Kings', 'Rajasthan Royals', 'Mumbai Indians',
       'Delhi Daredevils', 'Royal Challengers Bangalore',
       'Delhi Capitals', 'Sunrisers Hyderabad', 'Rising Pune Supergiants',
       'Punjab Kings', 'Kings XI Punjab', 'Kochi Tuskers Kerala',
       'Pune Warriors', 'Deccan Chargers', 'Kolkata Knight Riders',
       'Gujarat Titans', 'Rising Pune Supergiant', 'Gujarat Lions',
       'Lucknow Super Giants'], dtype=object)

In [35]:
team_name_map = {
    "Delhi Daredevils": "Delhi Capitals",
    "Kings XI Punjab": "Punjab Kings",
    "Royal Challengers Bangalore": "Royal Challengers Bengaluru",
    "Rising Pune Supergiants": "Rising Pune Supergiant"
}

df['Bat First'].replace(team_name_map, inplace=True)
df['Bat Second'].replace(team_name_map, inplace=True)
df['Winner'].replace(team_name_map, inplace=True)

In [36]:
df['Batter'].unique()

array(['RD Gaikwad', 'DP Conway', 'AM Rahane', 'S Dube', 'RA Jadeja',
       'MS Dhoni', 'N Jagadeesan', 'SP Narine', 'VR Iyer', 'N Rana',
       'JJ Roy', 'RK Singh', 'AD Russell', 'D Wiese', 'UT Yadav',
       'CV Varun', 'GC Smith', 'NV Ojha', 'SA Asnodkar', 'YK Pathan',
       'LA Carseldine', 'AS Raut', 'SK Warne', 'SM Harwood', 'M Vijay',
       'ML Hayden', 'SK Raina', 'S Badrinath', 'JDP Oram', 'RG Sharma',
       'Q de Kock', 'SA Yadav', 'SS Tiwary', 'KA Pollard', 'HH Pandya',
       'KH Pandya', 'NM Coulter-Nile', 'J Yadav', 'JJ Bumrah', 'PP Shaw',
       'S Dhawan', 'SPD Smith', 'RR Pant', 'SS Iyer', 'AR Patel',
       'SO Hetmyer', 'R Ashwin', 'LMP Simmons', 'PA Patel', 'AT Rayudu',
       'Harbhajan Singh', 'J Suchith', 'DR Smith', 'F du Plessis',
       'MEK Hussey', 'DJ Bravo', 'P Negi', 'MM Sharma', 'A Nehra',
       'G Gambhir', 'V Sehwag', 'TM Dilshan', 'MF Maharoof',
       'Shoaib Malik', 'SE Marsh', 'JR Hopes', 'Yuvraj Singh',
       'LA Pomersbach', 'DPMD Jayawardene', 'FY Fazal', 'R Dravid',
       'SR Watson', 'AL Menaria', 'PR Shah', 'AA Chavan', 'SW Tait',
       'ND Doshi', 'BB McCullum', 'BJ Hodge', 'CH Gayle', 'V Kohli',
       'UBT Chand', 'DA Warner', 'Y Venugopal Rao', 'LRPL Taylor',
       'IK Pathan', 'CA Ingram', 'KMA Paul', 'R Tewatia', 'BCJ Cutting',
       'MJ McClenaghan', 'Rasikh Salam', 'Abhishek Sharma',
       'KS Williamson', 'RA Tripathi', 'AK Markram', 'N Pooran',
       'Washington Sundar', 'Shashank Singh', 'M Jansen', 'WP Saha',
       'Shubman Gill', 'DA Miller', 'A Manohar', 'Rashid Khan',
       'KP Pietersen', 'NLTC Perera', 'M Vohra', 'GJ Maxwell',
       'MA Agarwal', 'JM Bairstow', 'LS Livingstone', 'JM Sharma',
       'M Shahrukh Khan', 'OF Smith', 'Ishan Kishan', 'D Brevis',
       'Tilak Varma', 'JD Unadkat', 'M Ashwin', 'TS Mills', 'L Ronchi',
       'ST Jayasuriya', 'RV Uthappa', 'SM Pollock', 'AM Nayar',
       'MA Khote', 'M Manhas', 'SV Samson', 'STR Binny', 'R Bhatia',
       'JP Faulkner', 'TG Southee', 'DS Kulkarni', 'PV Tambe',
       'RS Bopara', 'K Goel', 'KC Sangakkara', 'T Kohli', 'PP Chawla',
       'RE Levi', 'DJ Jacobs', 'KD Karthik', 'CJ McKay', 'RP Singh',
       'PP Ojha', 'MM Patel', 'JC Buttler', 'D Padikkal', 'DJ Mitchell',
       'R Parag', 'TA Boult', 'TH David', 'DR Sams', 'MK Tiwary',
       'JP Duminy', 'NJ Maddinson', 'KM Jadhav', 'RV Gomez',
       'R Vinay Kumar', 'RR Powar', 'MS Bisla', 'JH Kallis', 'EJG Morgan',
       'Shakib Al Hasan', 'B Lee', 'Iqbal Abdulla', 'L Balaji', 'KK Nair',
       'DJ Hooda', 'J Theron', 'JD Ryder', 'SC Ganguly', 'AD Mathews',
       'Y Nagar', 'M Morkel', 'AC Gilchrist', 'HH Gibbs', 'AA Bilakhia',
       'TL Suman', 'Shoaib Ahmed', 'AB de Villiers', 'YBK Jaiswal',
       'Dhruv Jurel', 'MM Ali', 'JA Morkel', 'SN Thakur',
       'Anmolpreet Singh', 'AF Milne', 'RD Chahar', 'B Chipli',
       'W Jaffer', 'Misbah-ul-Haq', 'MV Boucher', 'P Kumar', 'VVS Laxman',
       'Shahid Afridi', 'SB Styris', 'SB Bangar', 'AS Yadav',
       'MJ Guptill', 'MC Henriques', 'D Pretorius', 'KL Rahul',
       'MK Pandey', 'E Lewis', 'A Badoni', 'BA Stokes', 'AJ Turner',
       'SE Rutherford', 'CA Pujara', 'GJ Bailey', 'R Dhawan',
       'MG Johnson', 'Sandeep Sharma', 'CA Lynn', 'M Markande',
       'C de Grandhomme', 'Mandeep Singh', 'TM Head', 'Sachin Baby',
       'S Aravind', 'YS Chahal', 'A Choudhary', 'PK Garg', 'R Shepherd',
       'B Kumar', 'Umran Malik', 'PN Mankad', 'DJ Hussey',
       'Gurkeerat Singh', 'Azhar Mahmood', 'R Sathish', 'RJ Harris',
       'P Awana', 'PJ Cummins', 'KL Nagarkoti', 'S Gopal', 'JC Archer',
       'Kartik Tyagi', 'VR Aaron', 'Mohammad Nabi', 'Basil Thampi',
       'S Kaul', 'Mustafizur Rahman', 'RR Rossouw', 'SN Khan', 'HV Patel',
       'MA Starc', 'Harpreet Singh', 'NL McCullum', 'R Sharma', 'J Botha',
       'MJ Lumb', 'AA Jhunjhunwala', 'HC Brook', 'GD Phillips',
       'Abdul Samad', 'AU Rashid', 'MP Stoinis', 'V Shankar',
       'SW Billings', 'DL Chahar', 'B Sai Sudharsan', 'CL White',
       'BB Samantray', 'MJ Clarke', 'MN Samuels', 'SR Tendulkar',
       'DB Das', 'R McLaren', 'MD Mishra', 'A Symonds', 'MR Marsh',
       'B Sumanth', 'WPUJC Vaas', 'PD Collingwood', 'A Mishra',
       'S Vidyut', 'SP Fleming', 'CK Kapugedera', 'CJ Ferguson', 'S Rana',
       'WD Parnell', 'SP Goswami', 'JPR Scantlebury-Searles', 'AJ Finch',
       'AJ Tye', 'BB Sran', 'Abishek Porel', 'Aman Hakim Khan',
       'Kuldeep Yadav', 'A Nortje', 'DT Christian', 'KB Arun Karthik',
       'RT Ponting', 'CH Morris', 'B Laughlin', 'OC McCoy', 'MS Wade',
       'HM Amla', 'AD Nath', 'DJG Sammy', 'KV Sharma', 'SM Curran',
       'NS Naik', 'AP Tare', 'RM Patidar', 'Fazalhaq Farooqi',
       'Anureet Singh', 'Karanveer Singh', 'Mohammed Siraj', 'DR Shorey',
       'DW Steyn', 'KW Richardson', 'OA Shah', 'KK Cooper', 'PC Valthaty',
       'Bipul Sharma', 'Harmeet Singh', 'Sunny Singh', 'SL Malinga',
       'CJ Anderson', 'IR Jaggi', 'DB Ravi Teja', 'I Sharma',
       'A Ashish Reddy', 'GH Vihari', 'JDS Neesham', 'CJ Jordan',
       'DJ Harris', 'SMSM Senanayake', 'P Simran Singh',
       'Mujeeb Ur Rahman', 'Mohammed Shami', 'DJ Thornely',
       'S Chanderpaul', 'B Akhil', 'Lalit Yadav', 'R Powell',
       'Anirudh Singh', 'Jaskaran Singh', 'AB Barath', 'S Sreesanth',
       'R Rampaul', 'LJ Wright', 'AG Murtaza', 'IC Pandey', 'AB Dinda',
       'JR Philippe', 'Navdeep Saini', 'RN ten Doeschate', 'GB Hogg',
       'CR Brathwaite', 'Z Khan', 'Mohammad Hafeez', 'LR Shukla',
       'AB Agarkar', 'M Kartik', 'Anuj Rawat', 'SS Prabhudessai',
       'Shahbaz Ahmed', 'DL Vettori', 'A Mithun', 'KP Appanna',
       'A Kumble', 'Sohail Tanvir', 'M Kaif', 'M Rawat', 'SK Trivedi',
       'Mohammad Asif', 'VY Mahesh', 'GD McGrath', 'DM Bravo',
       'M Klinger', 'KS Bharat', 'KA Jamieson', 'JO Holder', 'R Shukla',
       'AD Mascarenhas', 'TK Curran', 'S Sohal', 'MJ Santner',
       'Salman Butt', 'A Chopra', 'T Taibu', 'AN Ghosh', 'N Wadhera',
       'Vishnu Vinod', 'C Green', 'Noor Ahmad', 'AS Joseph',
       'JA Richardson', 'UT Khawaja', 'LPC Silva', 'AS Rajpoot',
       'PBB Rajapaksa', 'Harpreet Brar', 'Rahmanullah Gurbaz',
       'PJ Sangwan', 'SD Lad', 'ER Dwivedi', 'AD Hales', 'RA Bawa',
       'TL Seifert', 'M Prasidh Krishna', 'HF Gurney', 'DJM Short',
       'K Gowtham', 'H Klaasen', 'NT Ellis', 'IS Sodhi',
       'RE van der Merwe', 'A Zampa', 'AS Roy', 'NK Patel', 'K Rabada',
       'TU Deshpande', 'MA Wood', 'Imran Tahir', 'TR Birt', 'KC Cariappa',
       'AP Dole', 'S Badree', 'WA Mota', 'I Malhotra', 'N Saini',
       'DH Yagnik', 'CM Gautam', 'FA Allen', 'SB Joshi', 'AG Paunikar',
       'A Singh', 'JM Kemp', 'MK Lomror', 'Ankit Sharma',
       'Ramandeep Singh', 'DS Lehmann', 'D Salunkhe', 'NJ Rimmington',
       'P Dogra', 'X Thalaivan Sargunam', 'Pankaj Singh', 'BJ Rohrer',
       'S Nadeem', 'JEC Franklin', 'MC Juneja', 'PA Reddy', 'S Ladda',
       'DP Nannes', 'BJ Haddin', 'RV Patel', 'KK Ahmed', 'S Anirudha',
       'CR Woakes', 'Swapnil Singh', 'K Kartikeya', 'JP Behrendorff',
       'GHS Garton', 'KR Mayers', 'SA Abbott', 'AN Ahmed', 'Younis Khan',
       'Kamran Akmal', 'HR Shokeen', 'Arshad Khan', 'BMAJ Mendis',
       'I Udana', 'LE Plunkett', 'SP Jackson', 'DJ Willey',
       'PWH de Silva', 'TM Srivastava', 'Umar Gul', 'AP Majumdar',
       'Vijaykumar Vyshak', 'TD Paine', 'SB Wagh', 'AC Thomas',
       'M Muralitharan', 'B Indrajith', 'Harshit Rana', 'Akash Deep',
       'JR Hazlewood', 'J Arunkumar', 'DT Patil', 'Abdur Razzak',
       'A Chandila', 'Abdul Basith', 'SM Katich', 'AC Voges',
       'SD Chitnis', 'CRD Fernando', 'VS Yeligati', 'AUK Pathan',
       'A Uniyal', 'MS Gony', 'P Sahu', 'RJ Peterson', 'L Ablish',
       'RS Sodhi', 'GC Viljoen', 'Avesh Khan', 'S Lamichhane',
       'AC Blizzard', 'YV Takawale', 'RR Raje', 'Arshdeep Singh',
       'VG Arora', 'S Kaushik', 'BR Dunk', 'Shivam Mavi', 'C Munro',
       'Atharva Taide', 'MW Short', 'MN van Wyk', 'H Das', 'DNT Zoysa',
       'BA Bhatt', 'D Kalyankrishna', 'RR Sarwan', 'Ravi Bishnoi',
       'Naveen-ul-Haq', 'SJ Srivastava', 'K Upadhyay', 'Y Prithvi Raj',
       'KJ Abbott', 'MDKJ Perera', 'VH Zol', 'CK Langeveldt', 'S Narwal',
       'RK Bhui', 'LH Ferguson', 'M de Lange', 'C Sakariya', 'K Yadav',
       'P Chopra', 'T Stubbs', 'YV Dhull', 'RR Bhatkal', 'KAJ Roach',
       'R Sanjay Yadav', 'A Mukund', 'SB Jakati', 'Yashpal Singh',
       'BAW Mendis', 'PD Salt', 'A Flintoff', 'Joginder Sharma',
       'T Thushara', 'JJ van der Wath', 'R Ninan', 'Yash Dayal',
       'Yudhvir Singh', 'JE Taylor', 'RJ Quiney', 'M Ntini',
       'Virat Singh', 'MD Shanaka', 'Sanvir Singh', 'KMDN Kulasekara',
       'VRV Singh', 'U Kaul', 'B Stanlake', 'Parvez Rasool',
       'DE Bollinger', 'Sunny Gupta', 'T Banton', 'S Tyagi', 'AA Noffke',
       'AB McDonald', 'RG More', 'T Henderson', 'SS Shaikh',
       'J Syed Mohammad', 'C Nanda', 'F Behardien', 'JL Pattinson',
       'BE Hendricks', 'AT Carey', 'PVD Chameera', 'RS Gavaskar',
       'SE Bond', 'C Madan', 'DJ Muthuswami', 'HE van der Dussen',
       'Mukesh Kumar', 'MG Bracewell', 'DJ Malan', 'T Natarajan',
       'P Ray Barman', 'A Tomar', 'Mukesh Choudhary', 'S Sriram',
       'Sikandar Raza', 'KS Sharma', 'Kamran Khan', 'P Parameswaran',
       'D du Preez', 'Liton Das', 'YA Abdulla', 'Simarjeet Singh',
       'M Theekshana', 'Vivrant Sharma', 'R Bishnoi', 'AJ Hosein',
       'Ankit Soni', 'Shivam Sharma', 'A Dananjaya', 'VS Malik',
       'P Dubey', 'Mashrafe Mortaza', 'SS Cottrell', 'JE Root', 'KM Asif',
       'Mohit Rathee', 'Mohsin Khan', 'S Randiv', 'RP Meredith',
       'JL Denly', 'GR Napier', 'FH Edwards', 'PM Sarvesh Kumar',
       'DP Vijaykumar', 'Mohammad Ashraful', 'V Pratap Singh', 'AR Bawne',
       'DR Martyn', 'Arjun Tendulkar', 'KR Sen', 'PSP Handscomb',
       'DAJ Bracewell', 'Shoaib Akhtar', 'Y Gnaneswara Rao', 'UA Birla',
       'DG Nalkande', 'T Shamsi'], dtype=object)

In [37]:
# Batter, Non Striker, Bowler
player_names_map = {
    "RD Gaikwad": "Ruturaj Gaikwad",
    "DP Conway": "Devon Conway",
    "AM Rahane": "Ajinkya Rahane",
    "S Dube": "Shivam Dube",
    "RA Jadeja": "Ravindra Jadeja",
    "Q de Kock": "Quinton de Kock",
    "SPD Smith": "Steve Smith",
    "AR Patel": "Axar Patel",
    "R Ashwin": "Ravichandran Ashwin",
    "F du Plessis": "Faf du Plessis",
    "G Gambhir": "Gautam Gambhir",
    "V Sehwag": "Virender Sehwag",
    "Yuvraj Singh": "Yuvraj Singh",
    "V Kohli": "Virat Kohli",
    "Rasikh Salam": "Rasikh Salam Dar",
    "Abhishek Sharma": "Abhishek Sharma",
    "Rashid Khan": "Rashid Khan",
    "Ishan Kishan": "Ishan Kishan",
    "Tilak Varma": "Tilak Varma",
    "Harbhajan Singh": "Harbhajan Singh",
    "Shakib Al Hasan": "Shakib Al Hasan",
    "Mohammad Nabi": "Mohammad Nabi",
    "Mustafizur Rahman": "Mustafizur Rahman",
    "Mohammed Siraj": "Mohammed Siraj",
    "Mohammed Shami": "Mohammed Shami",
    "Kuldeep Yadav": "Kuldeep Yadav",
    "Anmolpreet Singh": "Anmolpreet Singh",
    "Washington Sundar": "Washington Sundar",
    "Shubman Gill": "Shubman Gill",
    "Rahmanullah Gurbaz": "Rahmanullah Gurbaz",
    "Harshit Rana": "Harshit Rana",
    "Akash Deep": "Akash Deep",
    "Mukesh Kumar": "Mukesh Kumar",
    "Arshdeep Singh": "Arshdeep Singh",
    "Ravi Bishnoi": "Ravi Bishnoi",
    "Mohsin Khan": "Mohsin Khan",
    "Naveen-ul-Haq": "Naveen-ul-Haq",
    "Liton Das": "Litton Das",
    "T Stubbs": "Tristan Stubbs",
    "H Klaasen": "Heinrich Klaasen",
    "C Green": "Cameron Green",
    "M Theekshana": "Maheesh Theekshana",
    "HC Brook": "Harry Brook",
    "TM Head": "Travis Head",
    "KS Williamson": "Kane Williamson",
    "DJ Mitchell": "Daryl Mitchell",
    "MJ Santner": "Mitchell Santner",
    "FA Allen": "Finn Allen",
    "DJM Short": "Matthew Short",
    "MW Short": "Matthew Short",
    "PWH de Silva": "Wanindu Hasaranga",
    "AJ Hosein": "Akeal Hosein",
    "JE Root": "Joe Root",
    "BA Stokes": "Ben Stokes",
    "K Rabada": "Kagiso Rabada",
    "MA Wood": "Mark Wood",
    "NT Ellis": "Nathan Ellis",
    "JC Archer": "Jofra Archer",
    "JR Hazlewood": "Josh Hazlewood",
    "DW Steyn": "Dale Steyn",
    "PJ Cummins": "Pat Cummins",
    "MG Johnson": "Mitchell Johnson",
    "MJ McClenaghan": "Mitchell McClenaghan",
    "B Lee": "Brett Lee",
    "A Kumble": "Anil Kumble",
    "Z Khan": "Zaheer Khan",
    "MW Short": "Matthew Short",
    "DJM Short": "Matthew Short",
    "PWH de Silva": "Wanindu Hasaranga",
    "T Stubbs": "Tristan Stubbs",
    "H Klaasen": "Heinrich Klaasen",
    "C Green": "Cameron Green",
    "TM Head": "Travis Head",
    "M Theekshana": "Maheesh Theekshana",
    "AJ Hosein": "Akeal Hosein",
}

df['Batter'] = df['Batter'].replace(player_names_map).str.strip().str.title()
df['Non Striker'] = df['Non Striker'].replace(player_names_map).str.strip().str.title()
df['Bowler'] = df['Bowler'].replace(player_names_map).str.strip().str.title()

In [38]:
df.isnull().sum()

Match ID                        0
Date                            0
Venue                           0
Bat First                       0
Bat Second                      0
Innings                         0
Over                            0
Ball                            0
Batter                          0
Non Striker                     0
Bowler                          0
Batter Runs                     0
Extra Runs                      0
Runs From Ball                  0
Ball Rebowled                   0
Extra Type                      0
Wicket                          0
Method                     227866
Player Out                 227866
Innings Runs                    0
Innings Wickets                 0
Target Score                    0
Runs to Get                123927
Balls Remaining                 0
Winner                          0
Chased Successfully             0
Total Batter Runs               0
Total Non Striker Runs          0
Batter Balls Faced              0
Non Striker Balls Faced         0
Player Out Runs            227866
Player Out Balls Faced     227866
Bowler Runs Conceded            0
Valid Ball                      0
dtype: int64

In [39]:
df.dropna()

,Match ID,Date,Venue,Bat First,Bat Second,Innings,Over,Ball,Batter,Non Striker,...,Winner,Chased Successfully,Total Batter Runs,Total Non Striker Runs,Batter Balls Faced,Non Striker Balls Faced,Player Out Runs,Player Out Balls Faced,Bowler Runs Conceded,Valid Ball
126,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,1,4,Sp Narine,N Jagadeesan,...,Chennai Super Kings,0,0,1,0,1,0.0,3.0,0,1
130,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,2,2,N Jagadeesan,Vr Iyer,...,Chennai Super Kings,0,0,0,0,2,1.0,3.0,0,1
167,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,8,1,Vr Iyer,N Rana,...,Chennai Super Kings,0,0,22,0,18,20.0,20.0,0,1
174,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,9,2,N Rana,Jj Roy,...,Chennai Super Kings,0,0,19,0,4,27.0,21.0,0,1
213,1359507,2023-04-23,Eden Gardens,Chennai Super Kings,Kolkata Knight Riders,2,15,3,Jj Roy,Rk Singh,...,Chennai Super Kings,0,0,21,0,16,61.0,27.0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
239434,598012,2013-04-13,M. A. Chidambaram Stadium,Royal Challengers Bengaluru,Chennai Super Kings,2,19,1,Ms Dhoni,Ravindra Jadeja,...,Chennai Super Kings,1,0,26,0,16,33.0,24.0,0,1
239438,598012,2013-04-13,M. A. Chidambaram Stadium,Royal Challengers Bengaluru,Chennai Super Kings,2,19,4,Dj Bravo,Ravindra Jadeja,...,Chennai Super Kings,1,0,26,0,16,8.0,4.0,0,1
239624,1136596,2018-05-05,Rajiv Gandhi International Cricket Stadium,Delhi Capitals,Sunrisers Hyderabad,2,9,6,Ad Hales,S Dhawan,...,Sunrisers Hyderabad,1,0,28,0,24,45.0,31.0,0,1
239637,1136596,2018-05-05,Rajiv Gandhi International Cricket Stadium,Delhi Capitals,Sunrisers Hyderabad,2,11,6,S Dhawan,Kane Williamson,...,Sunrisers Hyderabad,1,0,4,0,6,33.0,31.0,0,1
239675,1136596,2018-05-05,Rajiv Gandhi International Cricket Stadium,Delhi Capitals,Sunrisers Hyderabad,2,18,1,Mk Pandey,Kane Williamson,...,Sunrisers Hyderabad,1,0,28,0,26,21.0,18.0,0,1

In [40]:
df.isnull().sum()

Match ID                        0
Date                            0
Venue                           0
Bat First                       0
Bat Second                      0
Innings                         0
Over                            0
Ball                            0
Batter                          0
Non Striker                     0
Bowler                          0
Batter Runs                     0
Extra Runs                      0
Runs From Ball                  0
Ball Rebowled                   0
Extra Type                      0
Wicket                          0
Method                     227866
Player Out                 227866
Innings Runs                    0
Innings Wickets                 0
Target Score                    0
Runs to Get                123927
Balls Remaining                 0
Winner                          0
Chased Successfully             0
Total Batter Runs               0
Total Non Striker Runs          0
Batter Balls Faced              0
Non Striker Balls Faced         0
Player Out Runs            227866
Player Out Balls Faced     227866
Bowler Runs Conceded            0
Valid Ball                      0
dtype: int64

In [41]:
# df['Method'].replace({'Plyer Out' : 'Not Out'}, inplace=True)
df['Method'].fillna('Not Out', inplace = True)
df['Player Out'].fillna('Player Out', inplace=True)
df['Runs to Get'].fillna(0, inplace=True)
df['Player Out Runs'].fillna(0, inplace=True)
df['Player Out Balls Faced'].fillna(0, inplace=True)

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 239693 entries, 0 to 239692
Data columns (total 34 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Match ID                 239693 non-null  int64
 1   Date                     239693 non-null  object
 2   Venue                    239693 non-null  object
 3   Bat First                239693 non-null  object
 4   Bat Second               239693 non-null  object
 5   Innings                  239693 non-null  int64
 6   Over                     239693 non-null  int64
 7   Ball                     239693 non-null  int64
 8   Batter                   239693 non-null  object
 9   Non Striker              239693 non-null  object
 10  Bowler                   239693 non-null  object
 11  Batter Runs              239693 non-null  int64
 12  Extra Runs               239693 non-null  int64
 13  Runs From Ball           239693 non-null  int64
 14  Ball Rebowled            239693 non-null  int64
 15  Extra Type               239693 non-null  object
 16  Wicket                   239693 non-null  int64
 17  Method                   239693 non-null  object
 18  Player Out               239693 non-null  object
 19  Innings Runs             239693 non-null  int64
 20  Innings Wickets          239693 non-null  int64
 21  Target Score             239693 non-null  int64
 22  Runs to Get              239693 non-null  float64
 23  Balls Remaining          239693 non-null  int64
 24  Winner                   239693 non-null  object
 25  Chased Successfully      239693 non-null  int64
 26  Total Batter Runs        239693 non-null  int64
 27  Total Non Striker Runs   239693 non-null  int64
 28  Batter Balls Faced       239693 non-null  int64
 29  Non Striker Balls Faced  239693 non-null  int64
 30  Player Out Runs          239693 non-null  float64
 31  Player Out Balls Faced   239693 non-null  float64
 32  Bowler Runs Conceded     239693 non-null  int64
 33  Valid Ball               239693 non-null  int64
dtypes: float64(3), int64(20), object(11)
memory usage: 64.0+ MB

In [43]:
df.duplicated().sum()

np.int64(0)

In [44]:
df['Match ID'] = df['Match ID'].astype('str')
df['Date'] = pd.to_datetime(df['Date'])
df['Ball Rebowled'] = df['Ball Rebowled'].astype('bool')
df['Runs to Get'] = df['Runs to Get'].astype('int')
df['Player Out Runs'] = df['Player Out Runs'].astype('int')
df['Player Out Balls Faced'] = df['Player Out Balls Faced'].astype('int')

In [45]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 239693 entries, 0 to 239692
Data columns (total 34 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   Match ID                 239693 non-null  object
 1   Date                     239693 non-null  datetime64[ns]
 2   Venue                    239693 non-null  object
 3   Bat First                239693 non-null  object
 4   Bat Second               239693 non-null  object
 5   Innings                  239693 non-null  int64
 6   Over                     239693 non-null  int64
 7   Ball                     239693 non-null  int64
 8   Batter                   239693 non-null  object
 9   Non Striker              239693 non-null  object
 10  Bowler                   239693 non-null  object
 11  Batter Runs              239693 non-null  int64
 12  Extra Runs               239693 non-null  int64
 13  Runs From Ball           239693 non-null  int64
 14  Ball Rebowled            239693 non-null  bool
 15  Extra Type               239693 non-null  object
 16  Wicket                   239693 non-null  int64
 17  Method                   239693 non-null  object
 18  Player Out               239693 non-null  object
 19  Innings Runs             239693 non-null  int64
 20  Innings Wickets          239693 non-null  int64
 21  Target Score             239693 non-null  int64
 22  Runs to Get              239693 non-null  int64
 23  Balls Remaining          239693 non-null  int64
 24  Winner                   239693 non-null  object
 25  Chased Successfully      239693 non-null  int64
 26  Total Batter Runs        239693 non-null  int64
 27  Total Non Striker Runs   239693 non-null  int64
 28  Batter Balls Faced       239693 non-null  int64
 29  Non Striker Balls Faced  239693 non-null  int64
 30  Player Out Runs          239693 non-null  int64
 31  Player Out Balls Faced   239693 non-null  int64
 32  Bowler Runs Conceded     239693 non-null  int64
 33  Valid Ball               239693 non-null  int64
dtypes: bool(1), datetime64[ns](1), int64(21), object(11)
memory usage: 62.4+ MB

# **Feature Engineering**

In [46]:
df['Year'] = df['Date'].dt.year

In [47]:
df['is_six'] = (df['Batter Runs'] == 6).astype(int)

In [48]:
df['Method'].unique()

array(['Not Out', 'bowled', 'caught', 'lbw', 'stumped', 'run out',
       'caught and bowled', 'retired hurt', 'hit wicket', 'retired out',
       'obstructing the field'], dtype=object)

In [49]:
valid_method = ['bowled', 'caught', 'lbw', 'stumped','caught and bowled','hit wicket']

df['bowler_wickets'] = df['Method'].isin(valid_method)

In [50]:
df['is_dot_balls'] = ((df['Runs From Ball'] == 0) & (df['Valid Ball'] == 1)).astype(int)